spring.datasource.url=${CRM_DB_URL:jdbc:postgresql://localhost:5432/crmdb}
spring.datasource.username=${CRM_DB_USERNAME:crmdb}
spring.datasource.password=${CRM_DB_PASSWORD:crmdb}
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

crm.entitlement.enabled=false
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:false}
